chat/urls.py
from unicodedata import name
from django.urls import path
from .views import chat_list, chat_main, chat_image

urlpatterns = [
    path('', chat_list, name='chat_list'),
    path('<slug:slug>/', chat_main, name='chat_main'),
    path('img/image_upload/', chat_image, name="chat_image")
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from notification.views import notifications

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('profile/', include('profiles.urls')),
    path('u/', include('app_auth.urls')),
    path('notifications/', notifications, name='notifications'),
    path('chat/', include('chat.urls'))


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

posts/models.py
from distutils.command.upload import upload
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile
from django.urls import reverse_lazy
import os

class Post(models.Model):
    content = models.TextField()
    image = models.FileField(upload_to='posts/', validators=[
                              FileExtensionValidator(['png', 'jpg', 'webp', 'jpeg', 'mp4', 'mkv'])])
    thumbnail_image = models.ImageField(upload_to='thumb/', blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()
    
    def num_comments(self):
        return self.comment_set.all().count()
    
    def get_absolute_url(self):
        return f'http://localhost:8000/post/{self.id}'
    
    def media_type(self):
        name, extension = os.path.splitext(self.image.name)
        image_ext = ['.png', '.jpg', '.jpeg', '.webp']
        video_ext = ['.mp4', '.mkv']

        for ext in image_ext:
            if ext == extension:
                return 'image'
        
        for ext in video_ext:
            if ext == extension:
                return 'video'
    


    class Meta:
        ordering = ('-created_at', )


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)
    
    class Meta:
        ordering = ('-created_at', )


LIKE_CHOISES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOISES, max_length=8)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} liked by {self.user} - {self.value}"

VERIFICATION_CHOISES = (
    ('Received', 'Received'),
    ('Verified', 'Verified')
)

class Verification(models.Model):

    class Job(models.IntegerChoices):
        BlogerActor = 1, "Bloger/Actor"
        Programmer = 2, "Programmer"
        FPlayer = 3, "Football Player"
        Sportsman = 4, "Sportsman"
        IT = 5, "Motion/Designer/IT",
        Other = 6, 'Other'

    
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    email = models.EmailField(max_length=255)
    verificated = models.CharField(
        choices=VERIFICATION_CHOISES,
        max_length=8,
        default='Received',
    )

    job = models.PositiveSmallIntegerField(
        choices=Job.choices,
        default=Job.Other
    )

    def __str__(self):
        return self.profile.user.username + '-' +  self.verificated

templates/include/create.html
<div class="modal"  id="create_modal">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head has-background-dark">
        <p class="modal-card-title has-text-white-ter pb-2">Create Post</p>
        <button class="delete" aria-label="close" onclick="toggleCreateModal()"></button>
      </header>
      <form  action="{% url 'home' %}" class="control" method="post" enctype="multipart/form-data">
        <section class="modal-card-body is-multiline columns">
          
            {% csrf_token %}
            <!-- {{ form }} -->
            {{ p_form.non_field_errors }}
  
            <div class="file has-name is-fullwidth is-12 column">
              <label class="file-label">
                {{ p_form.image }}
                <span class="file-cta">
                  <span class="file-icon">
                    <i   class="material-icons">
                      file_upload
                      </i>
                  </span>
                  <span class="file-label">
                    Choose a post media…
                  </span>
                </span>
                <span class="file-name">
                  [[ selectedFileName ]]
                </span>
              </label>
              {{ p_form.image.errors }}
            </div>
  
            <div class="field is-12 column">
              <label class="label is-small">Content</label>
              <div class="control">
                {{ p_form.content }}
              </div>
              {{ p_form.content.errors }}
            </div>
  
        </section>
  
        <footer class="modal-card-foot has-background-white">
          <button class="button is-primary" type="submit">Create</button>
          <button class="button" onclick="toggleCreateModal()">Cancel</button>
        </footer>
        
      </form>
  
    </div>
</div>

templates/include/exp_post_modal.html
<div class="modal modals-dskt" id="exp_modal{{ post.pk }}">
    
    {% include 'include/liked_users.html' %}
    {% include 'include/post_access.html' %}
    
    <div class="notification notif-copied is-info" v-show="isNotif">
        <button class="delete" @click="closeNotif"></button>
        Copied to clipboard
    </div>
    <div class="modal-background">
        <div class="navigate-arrow">
            <button data-prev_id="{{ post.pk }}" class="prev_to{{post.pk}} prev-to" onclick="prev_to_post('{{ post.pk }}')">
                <span class="material-icons ">
                    arrow_back_ios
                </span>
            </button>
            
            <button data-next_id="{{ post.pk }}" class="next_to{{post.pk}} next-to" onclick="next_to_post('{{ post.pk }}')">
                <span class="material-icons ">
                    arrow_forward_ios
                </span>
            </button>
        </div>
    </div>
    
    <div class="modal-card explore_post_modal">
        
        
      <section class="modal-card-body modal-body-exp">
       
        
        {% if post.media_type == 'image' %}
        <figure class="post-img" style="background-image: url('{{ post.image.url }}');">
            
        </figure>
        {% else %}
        <video 
          controls
          poster="{{ post.thumbnail_image }}"
          class="video-js video-media vd-for-modal"
          data-setup="{}"
          id="video{{ post.id }}"
          loop
          >
        
            <source src="{{ post.image.url }}" type="video/mp4">
        </video>
        {% endif %}
        <div class="modal-body-content">
            <header class="exp-header">
                <a href="{{ post.author.get_absolute_url }}">
                <div class="exp-post-author">
                    <div class="img-author author-exp" style="background-image: url('{{ post.author.avatar.url }}');">

                    </div>
                    <span class="d-flex" style="color: #333;">
                        {{ post.author }}

                        {% for verified in post.author.verification_set.all %}
                              {% if verified.verificated == 'Verified' %}
                                <i class="material-icons v-blue v-verif-post  " style="padding-top: .2rem;">
                                  verified
                                </i>
                              {% endif %}
                        {% endfor %}
                    </span>
                </div>
                </a>
                <div class="exp-opt-post">
                    <a @click="openAccessModal">
                        <span class="material-icons">
                            more_horiz
                        </span>
                    </a>
                </div>
            </header>

            
           
            <main class="exp-comments">
                <ul class="exp-comments-list" data-modalid="{{ post.pk }}">
                    {% for com in post.comment_set.all %}
                        <li >
                            <a href="{{ com.user.get_absolute_url }}">
                                <div class="img-author author-comment-exp" style="background-image: url('{{ com.user.avatar.url }}');"></div>
                            </a>

                            
                            <div class="exp-comment-main">
                                <span>
                                    {{ com.user }}
                                </span>
                                <p>
                                    {{ com.body }}
                                </p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </main>
            <footer class="exp-footer">
            <div class="exp-footer-top">
                    <form @submit.prevent="submitLikeForm" >
                        <button class="card-reaction-item like-item" name="sendLike" value="{{ post.id }}"  type="submit">
                            {% if my_profile not in post.liked.all %}<span class="material-icons like-btn-exp">favorite_border</span>{% else %}<span class="material-icons liked-btn-exp">favorite</span>{% endif %}
                        </button>
                    </form>
                    <a @click="focusInput({{ post.id }})"><i class="uil uil-comment-dots"></i></a>
                    <a><i class="uil uil-share-alt"></i></a>
                </div>
                <div class="exp-footer-likes-count">
                    <a class="open-modal" data-modal="modal{{ post.pk }}" style="color:#333">
                     <span> Likes: <p class="like-count{{ post.id }}" name="count">{{ post.num_likes }}</p></span>
                    </a>
                </div>
                <div class="exp-footer-bottom">
                    
                    <form style="border: 1px solid #DDD; display: flex;"  @submit.prevent="submitCommentForm">
                        <div class="img-author cmt-author-publ ml-3" style="background-image: url('{{ my_profile.avatar.url }}');">
                            
                        </div>
                        <input type="hidden" value="{{ post.pk }}" name="post_id">
                        <textarea type="text" ref="input{{post.pk}}" @input="onChanged" v-model="comment" placeholder="Type.." class="input" style="border: none;"></textarea>
                        
                        <div class="send-comment-exp">
                            <button type="submit" :disabled="isDisabled" style="font-size: 14px; ">
                                Publish
                            </button>
                        </div>
                    </form>
                </div>
            </footer>
        </div>
      </section>
    </div>
    <button class="modal-close modal-close-explore is-large" data-id="{{ post.pk }}" aria-label="close"></button>
</div>

templates/include/liked_users.html
<div class="modal-users">
    <div class="modal" id="modal{{ post.pk }}">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Like "marks"</p>
          <button class="delete is-medium close-modal-l" data-id="{{post.pk}}"></button>
        </header>
        <section class="modal-card-body">
            <ul class="reacted-user" id="reacted{{ post.id }}">
             {% for profile in post.like_set.all %}
               {% if profile.value == 'Like' %}
                <li class="mb-4" id="profile_{{ profile.user }}_{{ post.id }}">
                    <a href="{{ profile.user.get_absolute_url }}">
                      <figure class="img-react-user" style="background-image: url('{{ profile.user.avatar.url }}');">

                      </figure>
                      <div class="reacted-user-info">
                        <span>
                          {{ profile.user }}
                        </span>
                        <p>
                          {{ profile.user.first_name }}
                        </p>
                      </div>
                    </a>
                </li>
                {% endif  %}
             {% endfor %}
            </ul>
        </section>
      </div>
    </div>
    
</div>

templates/include/m_nav.html
<nav class="m-navbar">
    <div class="container">
        <div class="m-nav-list">
            <a class="m-nav-item" href="{% url 'home' %}">
                <span class="material-icons">
                    home
                </span>
            </a>
            <a class="m-nav-item" href="{% url 'pb_posts' %}">
                <span class="material-icons">
                    explore
                </span>
            </a>
            {% if request.path == '/' %}
                <a class="m-nav-item" onclick="toggleCreateModal()">
                    <span class="material-icons">add_circle</span>
                </a>
                {% else %}
                <a class="m-nav-item" href="{% url 'home' %}" >
                    <span class="material-icons">add_circle</span>
                </a>
            {% endif %}

            <a class="m-nav-item" href="{% url 'notifications' %}">
                <span class="material-icons">
                    notifications
                </span>
                {% if notifications.count > 0 %}
                <span  style="color:rgb(255, 41, 41); font-size: 13px; position: absolute; top: 10px;">
                    {{ notifications.count }}
                </span> 
                {% endif %}
            </a>
            <a class="m-nav-item" href="{% url 'my_profile' %}">
                <span class="material-icons">
                    account_circle
                </span>
            </a>

        </div>
    </div>
</nav>

templates/include/my_followers.html
<div class="modal-users">
    <div class="modal my-profile-following" id="my-profile-followers">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Followers</p>
          <button class="delete is-medium" id="close-myfw-modal"></button>
        </header>
        <section class="modal-card-body">
            <ul class="reacted-user">
             {% for profile in my_profile.follow.all %}
              <li class="mb-4">
                  <a href="{{ profile.get_absolute_url }}">
                    <figure class="img-react-user" style="background-image: url('{{ profile.avatar.url }}');">

                    </figure>
                    <div class="reacted-user-info">
                      <span>
                        {{ profile.user }}
                      </span>
                      <p>
                        {{ profile.first_name }}
                      </p>
                    </div>
                  </a>
              </li>
              {% empty %}
                <p class="mt-3 mb-3" style="text-align: center;">Oops No Followers</p>
             {% endfor %}
            </ul>
        </section>
      </div>
    </div>
    
</div>

templates/include/my_offcanvas.html
<div class="offcanvas-profile" @touchstart="handleTouchStart" @touchmove="handleTouchMove" id="myoffcanvas" :class="{'toggle-touch': isMenuActive}">
    <div class="container">
        <div class="m-menu-head">
            <span>

            </span>
        </div>
        <div class="m-menu-body">
            <ul>
                <li>
                    <a href="{% url 'verification' %}">
                        <span class="material-icons">
                            task_alt
                        </span>
                        
                        Get Verification
                    </a>
                </li>

                <li>
                    
                    <a href="">
                        <span class="material-icons">
                            lock_reset
                        </span>
                        Change Password
                    </a>
                </li>

                <li>
                    
                    <a href="{% url 'logout' %}">
                        <span class="material-icons">
                            logout
                            </span>
                        Log Out
                    </a>
                </li>
                
            </ul>
        </div>
    </div>
</div>

templates/include/nav.html
<nav class="navbar" role="navigation" aria-label="main navigation" id="nav">

  <sidebar class="navbar-brand">
      <a class="navbar-item" href="{% url 'home' %}" class="button is-text"
        style="text-decoration: none; font-size: 22px;">
        EnjoyChat
      </a>
    
    <!-- navbar-burger run  -->
    <a role="button" class="navbar-burger" @click="openMobileMenu" aria-label="menu" aria-expanded="false"
      data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a> 
    <!-- Navbar-burger end// -->

  </sidebar> <!-- navbar-brand end //-->

  <!-- Navbar-menu run //-->
  
    <div 
      id="navbarBasicExample" 
      class="navbar-menu" 
      v-bind:class="{ 'is-active': isMobileMenu }"
    >
      
      <!-- Navbar-start run -->

        <div class="navbar-start">

          <a class="navbar-item" href="{% url 'home' %}">
            <i class="material-icons md-dark">home</i>
            <span v-show="isMobileMenu" style="font-size: 18px;">Home</span>
          </a>

          <a class="navbar-item" href="{% url 'pb_posts' %}">
            <i class="material-icons md-dark">explore</i>
          </a>
          
          {% if request.path == '/' %}
            <a class="navbar-item" onclick="toggleCreateModal()">
              <i class="material-icons md-dark">add_circle</i>
            </a>
          {% else %}
            <a class="navbar-item" href="{% url 'home' %}" >
              <i class="material-icons md-dark">add_circle</i>
            </a>
          {% endif %}
          <a href="{% url 'chat_list' %}" class="navbar-item" >
            <i class="material-icons" style="font-size: 21px !important;">
              forum
              </i>
              {% if msg_notifs.count > 0 %}<span style="color:rgb(255, 41, 41);">{{ msg_notifs.count }}</span> {% endif %}
          </a>
         
       
          <a class="navbar-item" href="{% url 'notifications' %}">
            <i class="material-icons md-dark">notifications</i> {% if notifications.count > 0 %}<span style="color:rgb(255, 41, 41);">{{ notifications.count }}</span> {% endif %}
          </a>

         <div class="modal-search">
          <div class="search-box">
            <button class="btn-search" ref="btn_focus">
              <span class="material-icons" v-show="searchActive">
                search
              </span>
            </button>
            <button class="btn-search" ref="btn_focus2"  @click="closeSearchModal" >
              <span class="material-icons" style="color: black;" v-show="isCloseBtn">
                highlight_off
              </span>
            </button>
           
            <input type="text" @click="searchActive = false, isCloseBtn = true" v-model.trim="input"  @input="filterUsers"  class="input-search" placeholder="Type to Search...">
          </div>
          <div class="modal-list" v-show="isSeachModal">
            <div class="card">
                <ul class="card-list">
                  
                  <li class="link-li" v-for="user in filteredData" :key="user.id">
                    <a :href="user.get_absolute_url" class="d-flex list-link">
                      <figure class="list-img image  img-author-list" :style="{ backgroundImage:  'url(' + user.avatar + ')' }">
                      </figure>
                      <div class="list-user">
                          <span>[[ user.username ]]</span>
                          <p class="list-p-user">
                            [[ user.bio ]]
                          </p>
                      </div>
                   </a>
                  </li> 

                </ul>
            </div>
          </div>
         </div>
          

        </div> 

      <!-- Navbar-start end //-->

      <sidebar class="navbar-end pr-5" style="margin-bottom: 7px;">

        <div class="navbar-item">
          <div class="buttons">
            {% if request.user.is_authenticated %}
    
              <div class="dropdown is-hoverable" style="margin-bottom:-15px">
                <div class="dropdown-trigger">
                  <button class="button is-text">
                      <figure class="img-author mb-1" style="background-image: url('{{ my_profile.avatar.url }}');"></figure>
                    <!-- <span> <i class="material-icons md-dark">account_circle</i> </span> -->
                    <span class="pb-2 pl-2">{{ my_profile }}</span>
                  </button>
                </div>
    
                <div class="dropdown-menu" id="dropdown-menu" role="menu">
                  <div class="dropdown-content">
                    <a href="{% url 'my_profile' %}" class="dropdown-item">
                      My Profile
                    </a>
                    <a class="dropdown-item" href="#">
                      Change Password
                    </a>
                    <a class="dropdown-item r-verif" href="{% url 'verification' %}">
                      <span>Request Verification</span> 
                      <i class="material-icons">
                        verified
                      </i>
                    </a>
                  </div>
                </div> <!-- dropdown end//-->
    
              </div>
              <a class="navbar-item" href="{% url 'logout' %}">
                <i class="material-icons md-dark">exit_to_app</i>
              </a>
    
            {% else %}
    
              <a class="navbar-item">
                <button class="button is-primary">Sign Up</button>
              </a>
              <div class="navbar-item">
                <button class="button is-dark">Log In</button>
              </div>
    
            {% endif %}
            
          </div> <!-- buttons end //-->
        </div> <!-- navbar-item end// -->
    
      </sidebar>

    </div> 
  
  <!-- Navbar-menu end //-->

</nav>

templates/include/nav_home.html
<nav class="nav-home">
    <div class="container">
        <div class="nav-h-list">
            <div class="nav-h-item">
                <a href="{% url 'home' %}"><h3 class="subtitle is-4">EnjoyChat</h3></a>
            </div>
            <div class="nav-h-item">
                

                <a href="{% url 'chat_list' %}" class="d-flex" style="color: #333; align-items: center;">
                    <span class="material-icons">
                        question_answer
                    </span>
                    {% if msg_notifs.count > 0 %}<span style="color:rgb(255, 41, 41);" class="pb-3">{{ msg_notifs.count }}</span> {% endif %}

                </a>
            </div>
        </div>
    </div>
</nav>

templates/include/post_access.html
<div class="modal modal-access" :class="{ 'is-active': isPostAccess }">
  <div class="modal-background"></div>
  <div class="modal-card">
    
    <section class="modal-card-body modal-access-body">
      <div>
        <input type="text" class="hidden" value="{{ post.get_absolute_url }}" ref="copy{{ post.pk }}">
      </div>
      
      {% if request.user ==  post.author.user %}
        <a href="{% url 'post_delete' post.id %}" class="button access-button access-delete" >Delete</a>
      {% endif %}
      
      {% if request.path == '/public/' %}
      <a class="button access-button" href="{{ post.get_absolute_url }}">Go to Publication</a>
      {% endif %}
      <a class="button access-button"  @click="CopyToClipboard({{ post.pk }})">Copy Link</a>
      <a class="button access-button"  @click="openAccessModal">Cancel</a>

    </section>
    
  </div>
</div>

templates/include/profile_followed.html
<div class="modal-users">
    <div class="modal my-profile-following" id="my-profile-following">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">My Followed Users</p>
          <button class="delete is-medium" id="close-myf-modal"></button>
        </header>
        <section class="modal-card-body">
            <ul class="reacted-user">
             {% for profile in my_profile.followed.all %}
              <li class="mb-4">
                  <a href="{{ profile.get_absolute_url }}">
                    <figure class="img-react-user" style="background-image: url('{{ profile.avatar.url }}');">

                    </figure>
                    <div class="reacted-user-info">
                      <span>
                        {{ profile.user }}
                      </span>
                      <p>
                        {{ profile.first_name }}
                      </p>
                    </div>
                  </a>
              </li>
              {% empty %}
                <p class="mt-3 mb-3" style="text-align: center;">Oops No Followed Users</p>
             {% endfor %}
            </ul>
        </section>
      </div>
    </div>
    
</div>

templates/include/profile_modal.html
<div class="modal"  :class="{ 'is-active': isModalActive }" id="profile_modal">
  <div class="modal-background"></div>
  <div class="modal-card modal-myprofile-card">
    <header class="modal-card-head has-background-dark">
      <p class="modal-card-title has-text-white-ter pb-2">Edit Profile</p>
      
      <button class="delete"  @click="toggleProfileModal"></button>
    </header>
    <form action="{% url 'my_profile' %}" class="control" method="post" enctype="multipart/form-data">
      <section class="modal-card-body is-multiline modal-myprofile-body columns">
          {% csrf_token %}
          <!-- {{ form }} -->
          {{ form.non_field_errors }}


          <div class="file has-name is-fullwidth is-12 column">
            <label class="file-label">
              {{ form.avatar }}
              <span class="file-cta">
                <span class="file-icon">
                  <i  class="material-icons" style="padding-top: 3px !important;">
                    file_upload
                    </i>
                </span>
                <span class="file-label">
                  Choose a profile image…
                </span>
              </span>
              <span class="file-name">
                [[ selectedFileName ]]
              </span>
            </label>
            {{ form.avatar.errors }}
          </div>

          <div class="field is-6 column pt2-col-myprofile" style="margin-bottom: 0 !important;">
            <label class="label is-small">Name</label>
            <div class="control">
              {{ form.first_name }}
            </div>
            {{ form.first_name.errors }}
          </div>

          <div class="field is-6 column" style="margin-bottom: 0 !important;">
            <label class="label is-small">Last Name</label>
            <div class="control">
              {{ form.last_name }}
            </div>
            {{ form.last_name.errors }}
          </div>

          <div class="field is-12 column pt2-col-myprofile bio-col-myprofile">
            <label class="label is-small">Bio</label>
            <div class="control">
              {{ form.bio }}
            </div>
            {{ form.bio.errors }}
          </div>

      </section>

      <footer class="modal-card-foot has-background-white">
        <button class="button is-primary"  type="submit">Update</button>
        <button class="button"  @click="toggleProfileModal" type="button">Cancel</button>
      </footer>
      
    </form>

  </div>
</div>

templates/include/reaction_modal.html
  <!-- Modal -->

templates/include/user_followers.html
<div class="modal-users">
    <div class="modal my-profile-following"  :class="{ 'is-active': isUserFollowersActive}">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Followers</p>
          <button class="delete is-medium close-modal-l" @click="isUserFollowersActive = false"></button>
        </header>
        <section class="modal-card-body">
            <ul class="reacted-user">
             {% for profile in profile.follow.all %}
              <li class="mb-4" id="profile_{{ profile.user }}">
                  <a href="{{ profile.get_absolute_url }}" >
                    <figure class="img-react-user" style="background-image: url('{{ profile.avatar.url }}');">

                    </figure>
                    <div class="reacted-user-info">
                      <span>
                        {{ profile.user }}
                      </span>
                      <p>
                        {{ profile.first_name }}
                      </p>
                    </div>
                  </a>
              </li>
             {% endfor %}
            </ul>
        </section>
      </div>
    </div>
    
</div>

templates/include/user_followings.html
<div class="modal-users">
    <div class="modal my-profile-following"  :class="{ 'is-active': isUserFollowsActive}">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">Followings</p>
          <button class="delete is-medium close-modal-l" @click="isUserFollowsActive = false"></button>
        </header>
        <section class="modal-card-body">
            <ul class="reacted-user">
             {% for profile in profile.followed.all %}
              <li class="mb-4">
                  <a href="{{ profile.get_absolute_url }}">
                    <figure class="img-react-user" style="background-image: url('{{ profile.avatar.url }}');">

                    </figure>
                    <div class="reacted-user-info">
                      <span>
                        {{ profile.user }}
                      </span>
                      <p>
                        {{ profile.first_name }}
                      </p>
                    </div>
                  </a>
              </li>
              {% empty %}
                <p class="mt-3 mb-3" style="text-align: center;">Oops No Followings</p>
             {% endfor %}
            </ul>
        </section>
      </div>
    </div>
    
</div>